// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TriatlonProtocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace TriatlonProto {

  /// <summary>Holder for reflection information generated from TriatlonProtocol.proto</summary>
  public static partial class TriatlonProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for TriatlonProtocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TriatlonProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZUcmlhdGxvblByb3RvY29sLnByb3RvIjoKDlBhcnRpY2lwYW50RFRPEgoK",
            "AmlkGAEgASgDEgwKBG5hbWUYAiABKAkSDgoGcG9pbnRzGAMgASgFIlUKClJl",
            "ZmVyZWVEVE8SCgoCaWQYASABKAMSEAoIcGFzc3dvcmQYAiABKAkSGwoIdHJp",
            "YWxEdG8YAyABKAsyCS5UcmlhbERUTxIMCgRuYW1lGAQgASgJIm8KCFRyaWFs",
            "RFRPEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSKAoPcGFydGljaXBhbnRz",
            "RHRvGAMgAygLMg8uUGFydGljaXBhbnREVE8SHwoKcmVmZXJlZUR0bxgEIAEo",
            "CzILLlJlZmVyZWVEVE8ibQoJUmVzdWx0RFRPEgoKAmlkGAEgASgDEicKDnBh",
            "cnRpY2lwYW50RHRvGAIgASgLMg8uUGFydGljaXBhbnREVE8SGwoIdHJpYWxE",
            "dG8YAyABKAsyCS5UcmlhbERUTxIOCgZwb2ludHMYBCABKAUiXAoUUGFydGlj",
            "aXBhbnRUcmlhbERhdGESJwoOcGFydGljaXBhbnREdG8YASABKAsyDy5QYXJ0",
            "aWNpcGFudERUTxIbCgh0cmlhbER0bxgCIAEoCzIJLlRyaWFsRFRPIukCCgdS",
            "ZXF1ZXN0EhsKBHR5cGUYASABKA4yDS5SZXF1ZXN0LlR5cGUSIQoKcmVmZXJl",
            "ZUR0bxgCIAEoCzILLlJlZmVyZWVEVE9IABIpCg5wYXJ0aWNpcGFudER0bxgD",
            "IAEoCzIPLlBhcnRpY2lwYW50RFRPSAASHQoIdHJpYWxEdG8YBCABKAsyCS5U",
            "cmlhbERUT0gAEh8KCXJlc3VsdER0bxgFIAEoCzIKLlJlc3VsdERUT0gAEjUK",
            "FHBhcnRpY2lwYW50VHJpYWxEYXRhGAYgASgLMhUuUGFydGljaXBhbnRUcmlh",
            "bERhdGFIACJxCgRUeXBlEgkKBUxPR0lOEAASCgoGTE9HT1VUEAESFAoQR0VU",
            "X1BBUlRJQ0lQQU5UUxACEg4KCkFERF9SRVNVTFQQAxIXChNGSUxURVJfUEFS",
            "VElDSVBBTlRTEAQSEwoPUE9JTlRTX0FUX1RSSUFMEAVCCQoHcGF5bG9hZCKg",
            "AgoIUmVzcG9uc2USHAoEdHlwZRgBIAEoDjIOLlJlc3BvbnNlLlR5cGUSDQoF",
            "ZXJyb3IYAiABKAkSDgoGcG9pbnRzGAMgASgFEh0KCXJlc3VsdER0bxgEIAEo",
            "CzIKLlJlc3VsdERUTxIfCgpyZWZlcmVlRHRvGAUgASgLMgsuUmVmZXJlZURU",
            "TxIoCg9wYXJ0aWNpcGFudHNEdG8YBiADKAsyDy5QYXJ0aWNpcGFudERUTyJt",
            "CgRUeXBlEgYKAk9LEAASCQoFRVJST1IQARIQCgxQQVJUSUNJUEFOVFMQAhIZ",
            "ChVGSUxURVJFRF9QQVJUSUNJUEFOVFMQAxIQCgxSRVNVTFRfQURERUQQBBIT",
            "Cg9QT0lOVFNfQVRfVFJJQUwQBUIfQg1UcmlhdGxvblByb3RvqgINVHJpYXRs",
            "b25Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::TriatlonProto.ParticipantDTO), global::TriatlonProto.ParticipantDTO.Parser, new[]{ "Id", "Name", "Points" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TriatlonProto.RefereeDTO), global::TriatlonProto.RefereeDTO.Parser, new[]{ "Id", "Password", "TrialDto", "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TriatlonProto.TrialDTO), global::TriatlonProto.TrialDTO.Parser, new[]{ "Id", "Name", "ParticipantsDto", "RefereeDto" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TriatlonProto.ResultDTO), global::TriatlonProto.ResultDTO.Parser, new[]{ "Id", "ParticipantDto", "TrialDto", "Points" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TriatlonProto.ParticipantTrialData), global::TriatlonProto.ParticipantTrialData.Parser, new[]{ "ParticipantDto", "TrialDto" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TriatlonProto.Request), global::TriatlonProto.Request.Parser, new[]{ "Type", "RefereeDto", "ParticipantDto", "TrialDto", "ResultDto", "ParticipantTrialData" }, new[]{ "Payload" }, new[]{ typeof(global::TriatlonProto.Request.Types.Type) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::TriatlonProto.Response), global::TriatlonProto.Response.Parser, new[]{ "Type", "Error", "Points", "ResultDto", "RefereeDto", "ParticipantsDto" }, null, new[]{ typeof(global::TriatlonProto.Response.Types.Type) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ParticipantDTO : pb::IMessage<ParticipantDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParticipantDTO> _parser = new pb::MessageParser<ParticipantDTO>(() => new ParticipantDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParticipantDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TriatlonProto.TriatlonProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantDTO(ParticipantDTO other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      points_ = other.points_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantDTO Clone() {
      return new ParticipantDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "points" field.</summary>
    public const int PointsFieldNumber = 3;
    private int points_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Points {
      get { return points_; }
      set {
        points_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParticipantDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParticipantDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if (Points != other.Points) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Points != 0) hash ^= Points.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Points != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Points);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Points != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Points);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Points != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Points);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParticipantDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Points != 0) {
        Points = other.Points;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Points = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 24: {
            Points = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RefereeDTO : pb::IMessage<RefereeDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RefereeDTO> _parser = new pb::MessageParser<RefereeDTO>(() => new RefereeDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RefereeDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TriatlonProto.TriatlonProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefereeDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefereeDTO(RefereeDTO other) : this() {
      id_ = other.id_;
      password_ = other.password_;
      trialDto_ = other.trialDto_ != null ? other.trialDto_.Clone() : null;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RefereeDTO Clone() {
      return new RefereeDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "password" field.</summary>
    public const int PasswordFieldNumber = 2;
    private string password_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Password {
      get { return password_; }
      set {
        password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "trialDto" field.</summary>
    public const int TrialDtoFieldNumber = 3;
    private global::TriatlonProto.TrialDTO trialDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.TrialDTO TrialDto {
      get { return trialDto_; }
      set {
        trialDto_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RefereeDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RefereeDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Password != other.Password) return false;
      if (!object.Equals(TrialDto, other.TrialDto)) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Password.Length != 0) hash ^= Password.GetHashCode();
      if (trialDto_ != null) hash ^= TrialDto.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (trialDto_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TrialDto);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Password.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Password);
      }
      if (trialDto_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TrialDto);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Password.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
      }
      if (trialDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrialDto);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RefereeDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Password.Length != 0) {
        Password = other.Password;
      }
      if (other.trialDto_ != null) {
        if (trialDto_ == null) {
          TrialDto = new global::TriatlonProto.TrialDTO();
        }
        TrialDto.MergeFrom(other.TrialDto);
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            if (trialDto_ == null) {
              TrialDto = new global::TriatlonProto.TrialDTO();
            }
            input.ReadMessage(TrialDto);
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Password = input.ReadString();
            break;
          }
          case 26: {
            if (trialDto_ == null) {
              TrialDto = new global::TriatlonProto.TrialDTO();
            }
            input.ReadMessage(TrialDto);
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TrialDTO : pb::IMessage<TrialDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrialDTO> _parser = new pb::MessageParser<TrialDTO>(() => new TrialDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrialDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TriatlonProto.TriatlonProtocolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrialDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrialDTO(TrialDTO other) : this() {
      id_ = other.id_;
      name_ = other.name_;
      participantsDto_ = other.participantsDto_.Clone();
      refereeDto_ = other.refereeDto_ != null ? other.refereeDto_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrialDTO Clone() {
      return new TrialDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "participantsDto" field.</summary>
    public const int ParticipantsDtoFieldNumber = 3;
    private static readonly pb::FieldCodec<global::TriatlonProto.ParticipantDTO> _repeated_participantsDto_codec
        = pb::FieldCodec.ForMessage(26, global::TriatlonProto.ParticipantDTO.Parser);
    private readonly pbc::RepeatedField<global::TriatlonProto.ParticipantDTO> participantsDto_ = new pbc::RepeatedField<global::TriatlonProto.ParticipantDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TriatlonProto.ParticipantDTO> ParticipantsDto {
      get { return participantsDto_; }
    }

    /// <summary>Field number for the "refereeDto" field.</summary>
    public const int RefereeDtoFieldNumber = 4;
    private global::TriatlonProto.RefereeDTO refereeDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.RefereeDTO RefereeDto {
      get { return refereeDto_; }
      set {
        refereeDto_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrialDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrialDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Name != other.Name) return false;
      if(!participantsDto_.Equals(other.participantsDto_)) return false;
      if (!object.Equals(RefereeDto, other.RefereeDto)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      hash ^= participantsDto_.GetHashCode();
      if (refereeDto_ != null) hash ^= RefereeDto.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      participantsDto_.WriteTo(output, _repeated_participantsDto_codec);
      if (refereeDto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RefereeDto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      participantsDto_.WriteTo(ref output, _repeated_participantsDto_codec);
      if (refereeDto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(RefereeDto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      size += participantsDto_.CalculateSize(_repeated_participantsDto_codec);
      if (refereeDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RefereeDto);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrialDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      participantsDto_.Add(other.participantsDto_);
      if (other.refereeDto_ != null) {
        if (refereeDto_ == null) {
          RefereeDto = new global::TriatlonProto.RefereeDTO();
        }
        RefereeDto.MergeFrom(other.RefereeDto);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            participantsDto_.AddEntriesFrom(input, _repeated_participantsDto_codec);
            break;
          }
          case 34: {
            if (refereeDto_ == null) {
              RefereeDto = new global::TriatlonProto.RefereeDTO();
            }
            input.ReadMessage(RefereeDto);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            participantsDto_.AddEntriesFrom(ref input, _repeated_participantsDto_codec);
            break;
          }
          case 34: {
            if (refereeDto_ == null) {
              RefereeDto = new global::TriatlonProto.RefereeDTO();
            }
            input.ReadMessage(RefereeDto);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ResultDTO : pb::IMessage<ResultDTO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ResultDTO> _parser = new pb::MessageParser<ResultDTO>(() => new ResultDTO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ResultDTO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TriatlonProto.TriatlonProtocolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResultDTO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResultDTO(ResultDTO other) : this() {
      id_ = other.id_;
      participantDto_ = other.participantDto_ != null ? other.participantDto_.Clone() : null;
      trialDto_ = other.trialDto_ != null ? other.trialDto_.Clone() : null;
      points_ = other.points_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResultDTO Clone() {
      return new ResultDTO(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "participantDto" field.</summary>
    public const int ParticipantDtoFieldNumber = 2;
    private global::TriatlonProto.ParticipantDTO participantDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.ParticipantDTO ParticipantDto {
      get { return participantDto_; }
      set {
        participantDto_ = value;
      }
    }

    /// <summary>Field number for the "trialDto" field.</summary>
    public const int TrialDtoFieldNumber = 3;
    private global::TriatlonProto.TrialDTO trialDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.TrialDTO TrialDto {
      get { return trialDto_; }
      set {
        trialDto_ = value;
      }
    }

    /// <summary>Field number for the "points" field.</summary>
    public const int PointsFieldNumber = 4;
    private int points_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Points {
      get { return points_; }
      set {
        points_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ResultDTO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ResultDTO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (!object.Equals(ParticipantDto, other.ParticipantDto)) return false;
      if (!object.Equals(TrialDto, other.TrialDto)) return false;
      if (Points != other.Points) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (participantDto_ != null) hash ^= ParticipantDto.GetHashCode();
      if (trialDto_ != null) hash ^= TrialDto.GetHashCode();
      if (Points != 0) hash ^= Points.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (participantDto_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ParticipantDto);
      }
      if (trialDto_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TrialDto);
      }
      if (Points != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Points);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (participantDto_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(ParticipantDto);
      }
      if (trialDto_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TrialDto);
      }
      if (Points != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Points);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (participantDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipantDto);
      }
      if (trialDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrialDto);
      }
      if (Points != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Points);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ResultDTO other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.participantDto_ != null) {
        if (participantDto_ == null) {
          ParticipantDto = new global::TriatlonProto.ParticipantDTO();
        }
        ParticipantDto.MergeFrom(other.ParticipantDto);
      }
      if (other.trialDto_ != null) {
        if (trialDto_ == null) {
          TrialDto = new global::TriatlonProto.TrialDTO();
        }
        TrialDto.MergeFrom(other.TrialDto);
      }
      if (other.Points != 0) {
        Points = other.Points;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (participantDto_ == null) {
              ParticipantDto = new global::TriatlonProto.ParticipantDTO();
            }
            input.ReadMessage(ParticipantDto);
            break;
          }
          case 26: {
            if (trialDto_ == null) {
              TrialDto = new global::TriatlonProto.TrialDTO();
            }
            input.ReadMessage(TrialDto);
            break;
          }
          case 32: {
            Points = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 18: {
            if (participantDto_ == null) {
              ParticipantDto = new global::TriatlonProto.ParticipantDTO();
            }
            input.ReadMessage(ParticipantDto);
            break;
          }
          case 26: {
            if (trialDto_ == null) {
              TrialDto = new global::TriatlonProto.TrialDTO();
            }
            input.ReadMessage(TrialDto);
            break;
          }
          case 32: {
            Points = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ParticipantTrialData : pb::IMessage<ParticipantTrialData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParticipantTrialData> _parser = new pb::MessageParser<ParticipantTrialData>(() => new ParticipantTrialData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParticipantTrialData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TriatlonProto.TriatlonProtocolReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantTrialData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantTrialData(ParticipantTrialData other) : this() {
      participantDto_ = other.participantDto_ != null ? other.participantDto_.Clone() : null;
      trialDto_ = other.trialDto_ != null ? other.trialDto_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantTrialData Clone() {
      return new ParticipantTrialData(this);
    }

    /// <summary>Field number for the "participantDto" field.</summary>
    public const int ParticipantDtoFieldNumber = 1;
    private global::TriatlonProto.ParticipantDTO participantDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.ParticipantDTO ParticipantDto {
      get { return participantDto_; }
      set {
        participantDto_ = value;
      }
    }

    /// <summary>Field number for the "trialDto" field.</summary>
    public const int TrialDtoFieldNumber = 2;
    private global::TriatlonProto.TrialDTO trialDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.TrialDTO TrialDto {
      get { return trialDto_; }
      set {
        trialDto_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParticipantTrialData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParticipantTrialData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ParticipantDto, other.ParticipantDto)) return false;
      if (!object.Equals(TrialDto, other.TrialDto)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (participantDto_ != null) hash ^= ParticipantDto.GetHashCode();
      if (trialDto_ != null) hash ^= TrialDto.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (participantDto_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ParticipantDto);
      }
      if (trialDto_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrialDto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (participantDto_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ParticipantDto);
      }
      if (trialDto_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrialDto);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (participantDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipantDto);
      }
      if (trialDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrialDto);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParticipantTrialData other) {
      if (other == null) {
        return;
      }
      if (other.participantDto_ != null) {
        if (participantDto_ == null) {
          ParticipantDto = new global::TriatlonProto.ParticipantDTO();
        }
        ParticipantDto.MergeFrom(other.ParticipantDto);
      }
      if (other.trialDto_ != null) {
        if (trialDto_ == null) {
          TrialDto = new global::TriatlonProto.TrialDTO();
        }
        TrialDto.MergeFrom(other.TrialDto);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (participantDto_ == null) {
              ParticipantDto = new global::TriatlonProto.ParticipantDTO();
            }
            input.ReadMessage(ParticipantDto);
            break;
          }
          case 18: {
            if (trialDto_ == null) {
              TrialDto = new global::TriatlonProto.TrialDTO();
            }
            input.ReadMessage(TrialDto);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (participantDto_ == null) {
              ParticipantDto = new global::TriatlonProto.ParticipantDTO();
            }
            input.ReadMessage(ParticipantDto);
            break;
          }
          case 18: {
            if (trialDto_ == null) {
              TrialDto = new global::TriatlonProto.TrialDTO();
            }
            input.ReadMessage(TrialDto);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TriatlonProto.TriatlonProtocolReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      type_ = other.type_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.RefereeDto:
          RefereeDto = other.RefereeDto.Clone();
          break;
        case PayloadOneofCase.ParticipantDto:
          ParticipantDto = other.ParticipantDto.Clone();
          break;
        case PayloadOneofCase.TrialDto:
          TrialDto = other.TrialDto.Clone();
          break;
        case PayloadOneofCase.ResultDto:
          ResultDto = other.ResultDto.Clone();
          break;
        case PayloadOneofCase.ParticipantTrialData:
          ParticipantTrialData = other.ParticipantTrialData.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::TriatlonProto.Request.Types.Type type_ = global::TriatlonProto.Request.Types.Type.Login;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.Request.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "refereeDto" field.</summary>
    public const int RefereeDtoFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.RefereeDTO RefereeDto {
      get { return payloadCase_ == PayloadOneofCase.RefereeDto ? (global::TriatlonProto.RefereeDTO) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.RefereeDto;
      }
    }

    /// <summary>Field number for the "participantDto" field.</summary>
    public const int ParticipantDtoFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.ParticipantDTO ParticipantDto {
      get { return payloadCase_ == PayloadOneofCase.ParticipantDto ? (global::TriatlonProto.ParticipantDTO) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ParticipantDto;
      }
    }

    /// <summary>Field number for the "trialDto" field.</summary>
    public const int TrialDtoFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.TrialDTO TrialDto {
      get { return payloadCase_ == PayloadOneofCase.TrialDto ? (global::TriatlonProto.TrialDTO) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.TrialDto;
      }
    }

    /// <summary>Field number for the "resultDto" field.</summary>
    public const int ResultDtoFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.ResultDTO ResultDto {
      get { return payloadCase_ == PayloadOneofCase.ResultDto ? (global::TriatlonProto.ResultDTO) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ResultDto;
      }
    }

    /// <summary>Field number for the "participantTrialData" field.</summary>
    public const int ParticipantTrialDataFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.ParticipantTrialData ParticipantTrialData {
      get { return payloadCase_ == PayloadOneofCase.ParticipantTrialData ? (global::TriatlonProto.ParticipantTrialData) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.ParticipantTrialData;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      RefereeDto = 2,
      ParticipantDto = 3,
      TrialDto = 4,
      ResultDto = 5,
      ParticipantTrialData = 6,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(RefereeDto, other.RefereeDto)) return false;
      if (!object.Equals(ParticipantDto, other.ParticipantDto)) return false;
      if (!object.Equals(TrialDto, other.TrialDto)) return false;
      if (!object.Equals(ResultDto, other.ResultDto)) return false;
      if (!object.Equals(ParticipantTrialData, other.ParticipantTrialData)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::TriatlonProto.Request.Types.Type.Login) hash ^= Type.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.RefereeDto) hash ^= RefereeDto.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ParticipantDto) hash ^= ParticipantDto.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.TrialDto) hash ^= TrialDto.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ResultDto) hash ^= ResultDto.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.ParticipantTrialData) hash ^= ParticipantTrialData.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::TriatlonProto.Request.Types.Type.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.RefereeDto) {
        output.WriteRawTag(18);
        output.WriteMessage(RefereeDto);
      }
      if (payloadCase_ == PayloadOneofCase.ParticipantDto) {
        output.WriteRawTag(26);
        output.WriteMessage(ParticipantDto);
      }
      if (payloadCase_ == PayloadOneofCase.TrialDto) {
        output.WriteRawTag(34);
        output.WriteMessage(TrialDto);
      }
      if (payloadCase_ == PayloadOneofCase.ResultDto) {
        output.WriteRawTag(42);
        output.WriteMessage(ResultDto);
      }
      if (payloadCase_ == PayloadOneofCase.ParticipantTrialData) {
        output.WriteRawTag(50);
        output.WriteMessage(ParticipantTrialData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::TriatlonProto.Request.Types.Type.Login) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.RefereeDto) {
        output.WriteRawTag(18);
        output.WriteMessage(RefereeDto);
      }
      if (payloadCase_ == PayloadOneofCase.ParticipantDto) {
        output.WriteRawTag(26);
        output.WriteMessage(ParticipantDto);
      }
      if (payloadCase_ == PayloadOneofCase.TrialDto) {
        output.WriteRawTag(34);
        output.WriteMessage(TrialDto);
      }
      if (payloadCase_ == PayloadOneofCase.ResultDto) {
        output.WriteRawTag(42);
        output.WriteMessage(ResultDto);
      }
      if (payloadCase_ == PayloadOneofCase.ParticipantTrialData) {
        output.WriteRawTag(50);
        output.WriteMessage(ParticipantTrialData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::TriatlonProto.Request.Types.Type.Login) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (payloadCase_ == PayloadOneofCase.RefereeDto) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RefereeDto);
      }
      if (payloadCase_ == PayloadOneofCase.ParticipantDto) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipantDto);
      }
      if (payloadCase_ == PayloadOneofCase.TrialDto) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrialDto);
      }
      if (payloadCase_ == PayloadOneofCase.ResultDto) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResultDto);
      }
      if (payloadCase_ == PayloadOneofCase.ParticipantTrialData) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParticipantTrialData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::TriatlonProto.Request.Types.Type.Login) {
        Type = other.Type;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.RefereeDto:
          if (RefereeDto == null) {
            RefereeDto = new global::TriatlonProto.RefereeDTO();
          }
          RefereeDto.MergeFrom(other.RefereeDto);
          break;
        case PayloadOneofCase.ParticipantDto:
          if (ParticipantDto == null) {
            ParticipantDto = new global::TriatlonProto.ParticipantDTO();
          }
          ParticipantDto.MergeFrom(other.ParticipantDto);
          break;
        case PayloadOneofCase.TrialDto:
          if (TrialDto == null) {
            TrialDto = new global::TriatlonProto.TrialDTO();
          }
          TrialDto.MergeFrom(other.TrialDto);
          break;
        case PayloadOneofCase.ResultDto:
          if (ResultDto == null) {
            ResultDto = new global::TriatlonProto.ResultDTO();
          }
          ResultDto.MergeFrom(other.ResultDto);
          break;
        case PayloadOneofCase.ParticipantTrialData:
          if (ParticipantTrialData == null) {
            ParticipantTrialData = new global::TriatlonProto.ParticipantTrialData();
          }
          ParticipantTrialData.MergeFrom(other.ParticipantTrialData);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::TriatlonProto.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::TriatlonProto.RefereeDTO subBuilder = new global::TriatlonProto.RefereeDTO();
            if (payloadCase_ == PayloadOneofCase.RefereeDto) {
              subBuilder.MergeFrom(RefereeDto);
            }
            input.ReadMessage(subBuilder);
            RefereeDto = subBuilder;
            break;
          }
          case 26: {
            global::TriatlonProto.ParticipantDTO subBuilder = new global::TriatlonProto.ParticipantDTO();
            if (payloadCase_ == PayloadOneofCase.ParticipantDto) {
              subBuilder.MergeFrom(ParticipantDto);
            }
            input.ReadMessage(subBuilder);
            ParticipantDto = subBuilder;
            break;
          }
          case 34: {
            global::TriatlonProto.TrialDTO subBuilder = new global::TriatlonProto.TrialDTO();
            if (payloadCase_ == PayloadOneofCase.TrialDto) {
              subBuilder.MergeFrom(TrialDto);
            }
            input.ReadMessage(subBuilder);
            TrialDto = subBuilder;
            break;
          }
          case 42: {
            global::TriatlonProto.ResultDTO subBuilder = new global::TriatlonProto.ResultDTO();
            if (payloadCase_ == PayloadOneofCase.ResultDto) {
              subBuilder.MergeFrom(ResultDto);
            }
            input.ReadMessage(subBuilder);
            ResultDto = subBuilder;
            break;
          }
          case 50: {
            global::TriatlonProto.ParticipantTrialData subBuilder = new global::TriatlonProto.ParticipantTrialData();
            if (payloadCase_ == PayloadOneofCase.ParticipantTrialData) {
              subBuilder.MergeFrom(ParticipantTrialData);
            }
            input.ReadMessage(subBuilder);
            ParticipantTrialData = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::TriatlonProto.Request.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            global::TriatlonProto.RefereeDTO subBuilder = new global::TriatlonProto.RefereeDTO();
            if (payloadCase_ == PayloadOneofCase.RefereeDto) {
              subBuilder.MergeFrom(RefereeDto);
            }
            input.ReadMessage(subBuilder);
            RefereeDto = subBuilder;
            break;
          }
          case 26: {
            global::TriatlonProto.ParticipantDTO subBuilder = new global::TriatlonProto.ParticipantDTO();
            if (payloadCase_ == PayloadOneofCase.ParticipantDto) {
              subBuilder.MergeFrom(ParticipantDto);
            }
            input.ReadMessage(subBuilder);
            ParticipantDto = subBuilder;
            break;
          }
          case 34: {
            global::TriatlonProto.TrialDTO subBuilder = new global::TriatlonProto.TrialDTO();
            if (payloadCase_ == PayloadOneofCase.TrialDto) {
              subBuilder.MergeFrom(TrialDto);
            }
            input.ReadMessage(subBuilder);
            TrialDto = subBuilder;
            break;
          }
          case 42: {
            global::TriatlonProto.ResultDTO subBuilder = new global::TriatlonProto.ResultDTO();
            if (payloadCase_ == PayloadOneofCase.ResultDto) {
              subBuilder.MergeFrom(ResultDto);
            }
            input.ReadMessage(subBuilder);
            ResultDto = subBuilder;
            break;
          }
          case 50: {
            global::TriatlonProto.ParticipantTrialData subBuilder = new global::TriatlonProto.ParticipantTrialData();
            if (payloadCase_ == PayloadOneofCase.ParticipantTrialData) {
              subBuilder.MergeFrom(ParticipantTrialData);
            }
            input.ReadMessage(subBuilder);
            ParticipantTrialData = subBuilder;
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Request message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("LOGIN")] Login = 0,
        [pbr::OriginalName("LOGOUT")] Logout = 1,
        [pbr::OriginalName("GET_PARTICIPANTS")] GetParticipants = 2,
        [pbr::OriginalName("ADD_RESULT")] AddResult = 3,
        [pbr::OriginalName("FILTER_PARTICIPANTS")] FilterParticipants = 4,
        [pbr::OriginalName("POINTS_AT_TRIAL")] PointsAtTrial = 5,
      }

    }
    #endregion

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::TriatlonProto.TriatlonProtocolReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      points_ = other.points_;
      resultDto_ = other.resultDto_ != null ? other.resultDto_.Clone() : null;
      refereeDto_ = other.refereeDto_ != null ? other.refereeDto_.Clone() : null;
      participantsDto_ = other.participantsDto_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::TriatlonProto.Response.Types.Type type_ = global::TriatlonProto.Response.Types.Type.Ok;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.Response.Types.Type Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "points" field.</summary>
    public const int PointsFieldNumber = 3;
    private int points_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Points {
      get { return points_; }
      set {
        points_ = value;
      }
    }

    /// <summary>Field number for the "resultDto" field.</summary>
    public const int ResultDtoFieldNumber = 4;
    private global::TriatlonProto.ResultDTO resultDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.ResultDTO ResultDto {
      get { return resultDto_; }
      set {
        resultDto_ = value;
      }
    }

    /// <summary>Field number for the "refereeDto" field.</summary>
    public const int RefereeDtoFieldNumber = 5;
    private global::TriatlonProto.RefereeDTO refereeDto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::TriatlonProto.RefereeDTO RefereeDto {
      get { return refereeDto_; }
      set {
        refereeDto_ = value;
      }
    }

    /// <summary>Field number for the "participantsDto" field.</summary>
    public const int ParticipantsDtoFieldNumber = 6;
    private static readonly pb::FieldCodec<global::TriatlonProto.ParticipantDTO> _repeated_participantsDto_codec
        = pb::FieldCodec.ForMessage(50, global::TriatlonProto.ParticipantDTO.Parser);
    private readonly pbc::RepeatedField<global::TriatlonProto.ParticipantDTO> participantsDto_ = new pbc::RepeatedField<global::TriatlonProto.ParticipantDTO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::TriatlonProto.ParticipantDTO> ParticipantsDto {
      get { return participantsDto_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (Points != other.Points) return false;
      if (!object.Equals(ResultDto, other.ResultDto)) return false;
      if (!object.Equals(RefereeDto, other.RefereeDto)) return false;
      if(!participantsDto_.Equals(other.participantsDto_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::TriatlonProto.Response.Types.Type.Ok) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (Points != 0) hash ^= Points.GetHashCode();
      if (resultDto_ != null) hash ^= ResultDto.GetHashCode();
      if (refereeDto_ != null) hash ^= RefereeDto.GetHashCode();
      hash ^= participantsDto_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::TriatlonProto.Response.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (Points != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Points);
      }
      if (resultDto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ResultDto);
      }
      if (refereeDto_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RefereeDto);
      }
      participantsDto_.WriteTo(output, _repeated_participantsDto_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::TriatlonProto.Response.Types.Type.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (Points != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Points);
      }
      if (resultDto_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ResultDto);
      }
      if (refereeDto_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(RefereeDto);
      }
      participantsDto_.WriteTo(ref output, _repeated_participantsDto_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::TriatlonProto.Response.Types.Type.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (Points != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Points);
      }
      if (resultDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ResultDto);
      }
      if (refereeDto_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RefereeDto);
      }
      size += participantsDto_.CalculateSize(_repeated_participantsDto_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::TriatlonProto.Response.Types.Type.Ok) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.Points != 0) {
        Points = other.Points;
      }
      if (other.resultDto_ != null) {
        if (resultDto_ == null) {
          ResultDto = new global::TriatlonProto.ResultDTO();
        }
        ResultDto.MergeFrom(other.ResultDto);
      }
      if (other.refereeDto_ != null) {
        if (refereeDto_ == null) {
          RefereeDto = new global::TriatlonProto.RefereeDTO();
        }
        RefereeDto.MergeFrom(other.RefereeDto);
      }
      participantsDto_.Add(other.participantsDto_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::TriatlonProto.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 24: {
            Points = input.ReadInt32();
            break;
          }
          case 34: {
            if (resultDto_ == null) {
              ResultDto = new global::TriatlonProto.ResultDTO();
            }
            input.ReadMessage(ResultDto);
            break;
          }
          case 42: {
            if (refereeDto_ == null) {
              RefereeDto = new global::TriatlonProto.RefereeDTO();
            }
            input.ReadMessage(RefereeDto);
            break;
          }
          case 50: {
            participantsDto_.AddEntriesFrom(input, _repeated_participantsDto_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::TriatlonProto.Response.Types.Type) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 24: {
            Points = input.ReadInt32();
            break;
          }
          case 34: {
            if (resultDto_ == null) {
              ResultDto = new global::TriatlonProto.ResultDTO();
            }
            input.ReadMessage(ResultDto);
            break;
          }
          case 42: {
            if (refereeDto_ == null) {
              RefereeDto = new global::TriatlonProto.RefereeDTO();
            }
            input.ReadMessage(RefereeDto);
            break;
          }
          case 50: {
            participantsDto_.AddEntriesFrom(ref input, _repeated_participantsDto_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Response message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum Type {
        [pbr::OriginalName("OK")] Ok = 0,
        [pbr::OriginalName("ERROR")] Error = 1,
        [pbr::OriginalName("PARTICIPANTS")] Participants = 2,
        [pbr::OriginalName("FILTERED_PARTICIPANTS")] FilteredParticipants = 3,
        [pbr::OriginalName("RESULT_ADDED")] ResultAdded = 4,
        [pbr::OriginalName("POINTS_AT_TRIAL")] PointsAtTrial = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
